name: Build jiuchuan-s3

on:
  push:
    branches:
      - main
      - ci/* # for ci test
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build jiuchuan-s3
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build jiuchuan-s3
        shell: bash
        run: |
          source $IDF_PATH/export.sh
          python scripts/release.py jiuchuan-s3 --name jiuchuan-s3

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: personal_assistant_jiuchuan-s3_${{ github.sha }}.bin
          path: build/merged-binary.bin
          if-no-files-found: error

  build-headless:
    name: Build jiuchuan-s3-headless (无屏语音助手)
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build jiuchuan-s3-headless
        shell: bash
        run: |
          source $IDF_PATH/export.sh
          python scripts/release.py jiuchuan-s3 --name jiuchuan-s3-headless

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: personal_assistant_jiuchuan-s3-headless_${{ github.sha }}.bin
          path: build/merged-binary.bin
          if-no-files-found: error